#!/usr/bin/bash

function get_proc {
    ls ~/test > "file_list"
    array=()
    while read -r line; do
        element="$line"
        array+=("$element")
    done < "file_list"
}

get_proc
previous_array=("${array[@]}")
while sleep 5; do
    get_proc
    echo ----------
    echo "${previous_array[*]}"
    echo "${array[*]}"
    new_proc_array=()
    for element1 in "${array[@]}"; do
        skip=
        for element2 in "${previous_array[@]}"; do
            [[ $element1 == $element2 ]] && { skip=1; break; }
        done
        [[ -n $skip ]] || new_proc_array+=("$element1")
    done
    echo "${new_proc_array[*]}"
    previous_array=("${array[@]}")
done



